### ISSUE TITLE
Manjaro/Arch Compilation error libftdi 

### ISSUE THREAD

**Issue by loucass003** [mcallegari/qlcplus#1272]
im building glcplus (4.12.3) on Manjaro, i tried from the aur and tried to build it myself

i suppose there is a dependency version issue with libftdi and libusb

```
g++ -c -Wno-deprecated-declarations -Wno-deprecated-copy -Werror -Wno-unused-local-typedefs -O2 -Wall -Wextra -D_REENTRANT -fPIC -DQT_NO_DEBUG_OUTPUT -DLIBFTDI1 -DQT_NO_DEBUG -DQT_PLUGIN -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -I../../interfaces -I../../midi/src/common -I/usr/include/libftdipp1 -I/usr/include/libusb-1.0 -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I. -I/usr/lib/qt/mkspecs/linux-g++ -o libftdi-interface.o libftdi-interface.cpp
libftdi-interface.cpp: In static member function ‘static QList<DMXInterface*> LibFTDIInterface::interfaces(QList<DMXInterface*>)’:
libftdi-interface.cpp:138:37: error: ‘struct ftdi_context’ has no member named ‘usb_ctx’
  138 |     if (libusb_get_device_list(ftdi.usb_ctx, &devs) < 0)
      |                                     ^~~~~~~
libftdi-interface.cpp:182:37: error: cannot convert ‘libusb_device*’ to ‘usb_device*’
  182 |         ftdi_usb_get_strings(&ftdi, dev, vend, 256, nme, 256, ser, 256);
      |                                     ^~~
      |                                     |
      |                                     libusb_device*
In file included from libftdi-interface.h:24,
                 from libftdi-interface.cpp:31:
/usr/include/ftdi.h:376:76: note:   initializing argument 2 of ‘int ftdi_usb_get_strings(ftdi_context*, usb_device*, char*, int, char*, int, char*, int)’
  376 |     int ftdi_usb_get_strings(struct ftdi_context *ftdi, struct usb_device *dev,
      |                                                         ~~~~~~~~~~~~~~~~~~~^~~
In file included from libftdi-interface.cpp:28:
/usr/include/libusb-1.0/libusb.h:944:8: note: class type ‘libusb_device’ is incomplete
  944 | struct libusb_device;
      |        ^~~~~~~~~~~~~
make[3]: *** [Makefile:745: libftdi-interface.o] Error 1
make[3]: Leaving directory '/home/llelievr/Downloads/qlcplus/plugins/dmxusb/src'
make[2]: *** [Makefile:47: sub-src-make_first-ordered] Error 2
make[2]: Leaving directory '/home/llelievr/Downloads/qlcplus/plugins/dmxusb'
make[1]: *** [Makefile:60: sub-dmxusb-make_first] Error 2
make[1]: Leaving directory '/home/llelievr/Downloads/qlcplus/plugins'
make: *** [Makefile:356: sub-plugins-make_first-ordered] Error 2

```

I never made an issue on github. Please tell me if something is missing.

**Comment by DrumSlayers** [comment]
Same issue with glcplus 4.12.3 on Manjaro 20.2.1, Linux 5.10.15.
Exactly the same error

**Comment by mcallegari** [comment]
Which version of libusb is installed in the system?

**Comment by loucass003** [comment]
libusb (1.0.24-2)

```➜  ~ pacman -Q --info libusb
Name            : libusb
Version         : 1.0.24-2
Description     : Library that provides generic access to USB devices
Architecture    : x86_64
URL             : https://libusb.info/
Licenses        : LGPL2.1
Groups          : None
Provides        : libusb-1.0.so=0-64
Depends On      : glibc  libudev.so=1-64
Optional Deps   : None
Required By     : gst-plugins-bad-libs  lib32-libusb  libcups  libdc1394
                  libftdi  libgphoto2  libgusb  libmtp  libusb-compat
                  libusbmuxd  sane  sdl2  upower  usb_modeswitch  usbutils
Optional For    : grub  gutenprint  hidapi  hplip
Conflicts With  : None
Replaces        : None
Installed Size  : 204.22 KiB
Packager        : David Runge <dvzrv@archlinux.org>
Build Date      : Sun 10 Jan 2021 08:20:37 PM CET
Install Date    : Thu 04 Mar 2021 05:21:24 PM CET
Install Reason  : Installed as a dependency for another package
Install Script  : No
Validated By    : Signature
```

**Comment by mcallegari** [comment]
Ok, I also need the libftdi version (should be > 1.x)

**Comment by loucass003** [comment]
libftdi (1.5-1)

```
Name            : libftdi
Version         : 1.5-1
Description     : A library to talk to FTDI chips, optional python bindings.
Architecture    : x86_64
URL             : https://www.intra2net.com/en/developer/libftdi/download.php
Licenses        : GPL2  LGPL2.1
Groups          : None
Provides        : None
Depends On      : libusb  confuse
Optional Deps   : python: library bindings [installed]
Required By     : flashrom  lirc
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 536.96 KiB
Packager        : Kyle Keen <keenerd@gmail.com>
Build Date      : Sun 20 Dec 2020 02:54:00 AM CET
Install Date    : Sun 03 Jan 2021 12:07:02 PM CET
Install Reason  : Installed as a dependency for another package
Install Script  : No
Validated By    : Signature

```

**Comment by loucass003** [comment]
Any idea on when this is going to be fixed ?
i really need qlcplus ^^

**Comment by mcallegari** [comment]
Please run these two too:
```
pkg-config --modversion libusb
pkg-config --modversion libftdi
```
I use Ubuntu. I have no way to reproduce the error.

**Comment by DrumSlayers** [comment]
> Please run these two too:
> 
> ```
> pkg-config --modversion libusb
> pkg-config --modversion libftdi
> ```
> 
> I use Ubuntu. I have no way to reproduce the error.

Here are the results:
`[drumslayer@DrumSlayer-LaptopHP-Manjaro ~]$ pkg-config --modversion libusb
0.1.12
[drumslayer@DrumSlayer-LaptopHP-Manjaro ~]$ pkg-config --modversion libftdi
0.20
`

**Comment by mcallegari** [comment]
And one more, sorry:
`pkg-config --modversion libftdi1`
I believe there's a mismatch between the selected libftdi version and the libusb version.
Please also tell me if you see a message saying "Building with libFTDI1 support." when QLC+ builds the dmxusb plugin

**Comment by DrumSlayers** [comment]
> And one more, sorry:
> `pkg-config --modversion libftdi1`
> I believe there's a mismatch between the selected libftdi version and the libusb version.
> Please also tell me if you see a message saying "Building with libFTDI1 support." when QLC+ builds the dmxusb plugin

```
[drumslayer@DrumSlayer-LaptopHP-Manjaro ~]$ pkg-config --modversion libftdi1
1.5
```
Ok, I come back later, i will give you the full compilation logs in full verbose++, so you can have the whole process :)

**Comment by mcallegari** [comment]
Ooops, I edited the previous. I need two outputs.

**Comment by mcallegari** [comment]
> Ok, I come back later, i will give you the full compilation logs in full verbose++, so you can have the whole process :)

I think there's no need for the whole process. Just the dmxusb plugin build output
```
cd plugins/dmxusb
make distclean
cd ..
make
```

**Comment by DrumSlayers** [comment]
Sorry for the latency, i was busy :/
Here is the added line
```
[drumslayer@DrumSlayer-LaptopHP-Manjaro git]$ pkg-config --modversion libusb-1.0
1.0.24
```

And the plugins make:
```
[drumslayer@DrumSlayer-LaptopHP-Manjaro dmxusb]$ make distclean
cd src/ && ( test -e Makefile || /usr/bin/qmake -o Makefile /home/drumslayer/git/qlcplus/plugins/dmxusb/src/src.pro ) && make -f Makefile distclean
make[1] : on entre dans le répertoire « /home/drumslayer/git/qlcplus/plugins/dmxusb/src »
rm -f moc_predefs.h
rm -f moc_qlcioplugin.cpp moc_dmxusb.cpp moc_dmxusbconfig.cpp moc_enttecdmxusbpro.cpp moc_enttecdmxusbopen.cpp moc_dmxusbopenrx.cpp
rm -f qlcioplugin.o dmxinterface.o dmxusb.o dmxusbwidget.o dmxusbconfig.o enttecdmxusbpro.o enttecdmxusbopen.o dmxusbopenrx.o stageprofi.o vinceusbdmx512.o midiprotocol.o nanodmx.o euroliteusbdmxpro.o libftdi-interface.o moc_qlcioplugin.o moc_dmxusb.o moc_dmxusbconfig.o moc_enttecdmxusbpro.o moc_enttecdmxusbopen.o moc_dmxusbopenrx.o
rm -f *~ core *.core
rm -f libdmxusb.so 
rm -f Makefile
make[1] : on quitte le répertoire « /home/drumslayer/git/qlcplus/plugins/dmxusb/src »
rm -f Makefile
[drumslayer@DrumSlayer-LaptopHP-Manjaro dmxusb]$ cd ..
[drumslayer@DrumSlayer-LaptopHP-Manjaro plugins]$ make
cd dmxusb/ && ( test -e Makefile || /usr/bin/qmake -o Makefile /home/drumslayer/git/qlcplus/plugins/dmxusb/dmxusb.pro ) && make -f Makefile 
make[1] : on entre dans le répertoire « /home/drumslayer/git/qlcplus/plugins/dmxusb »
cd src/ && ( test -e Makefile || /usr/bin/qmake -o Makefile /home/drumslayer/git/qlcplus/plugins/dmxusb/src/src.pro ) && make -f Makefile 
Project MESSAGE: Building with libFTDI1 support.
make[2] : on entre dans le répertoire « /home/drumslayer/git/qlcplus/plugins/dmxusb/src »
g++ -c -pipe -Werror -Wno-unused-local-typedefs -g -Wall -Wextra -D_REENTRANT -fPIC -DLIBFTDI1 -DQT_PLUGIN -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -I../../interfaces -I../../midi/src/common -I/usr/include/libftdipp1 -I/usr/include/libusb-1.0 -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I. -I/usr/lib/qt/mkspecs/linux-g++ -o qlcioplugin.o ../../interfaces/qlcioplugin.cpp
g++ -c -pipe -Werror -Wno-unused-local-typedefs -g -Wall -Wextra -D_REENTRANT -fPIC -DLIBFTDI1 -DQT_PLUGIN -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -I../../interfaces -I../../midi/src/common -I/usr/include/libftdipp1 -I/usr/include/libusb-1.0 -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I. -I/usr/lib/qt/mkspecs/linux-g++ -o dmxinterface.o dmxinterface.cpp
g++ -c -pipe -Werror -Wno-unused-local-typedefs -g -Wall -Wextra -D_REENTRANT -fPIC -DLIBFTDI1 -DQT_PLUGIN -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -I../../interfaces -I../../midi/src/common -I/usr/include/libftdipp1 -I/usr/include/libusb-1.0 -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I. -I/usr/lib/qt/mkspecs/linux-g++ -o dmxusb.o dmxusb.cpp
g++ -c -pipe -Werror -Wno-unused-local-typedefs -g -Wall -Wextra -D_REENTRANT -fPIC -DLIBFTDI1 -DQT_PLUGIN -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -I../../interfaces -I../../midi/src/common -I/usr/include/libftdipp1 -I/usr/include/libusb-1.0 -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I. -I/usr/lib/qt/mkspecs/linux-g++ -o dmxusbwidget.o dmxusbwidget.cpp
g++ -c -pipe -Werror -Wno-unused-local-typedefs -g -Wall -Wextra -D_REENTRANT -fPIC -DLIBFTDI1 -DQT_PLUGIN -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -I../../interfaces -I../../midi/src/common -I/usr/include/libftdipp1 -I/usr/include/libusb-1.0 -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I. -I/usr/lib/qt/mkspecs/linux-g++ -o dmxusbconfig.o dmxusbconfig.cpp
g++ -c -pipe -Werror -Wno-unused-local-typedefs -g -Wall -Wextra -D_REENTRANT -fPIC -DLIBFTDI1 -DQT_PLUGIN -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -I../../interfaces -I../../midi/src/common -I/usr/include/libftdipp1 -I/usr/include/libusb-1.0 -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I. -I/usr/lib/qt/mkspecs/linux-g++ -o enttecdmxusbpro.o enttecdmxusbpro.cpp
g++ -c -pipe -Werror -Wno-unused-local-typedefs -g -Wall -Wextra -D_REENTRANT -fPIC -DLIBFTDI1 -DQT_PLUGIN -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -I../../interfaces -I../../midi/src/common -I/usr/include/libftdipp1 -I/usr/include/libusb-1.0 -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I. -I/usr/lib/qt/mkspecs/linux-g++ -o enttecdmxusbopen.o enttecdmxusbopen.cpp
g++ -c -pipe -Werror -Wno-unused-local-typedefs -g -Wall -Wextra -D_REENTRANT -fPIC -DLIBFTDI1 -DQT_PLUGIN -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -I../../interfaces -I../../midi/src/common -I/usr/include/libftdipp1 -I/usr/include/libusb-1.0 -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I. -I/usr/lib/qt/mkspecs/linux-g++ -o dmxusbopenrx.o dmxusbopenrx.cpp
g++ -c -pipe -Werror -Wno-unused-local-typedefs -g -Wall -Wextra -D_REENTRANT -fPIC -DLIBFTDI1 -DQT_PLUGIN -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -I../../interfaces -I../../midi/src/common -I/usr/include/libftdipp1 -I/usr/include/libusb-1.0 -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I. -I/usr/lib/qt/mkspecs/linux-g++ -o stageprofi.o stageprofi.cpp
g++ -c -pipe -Werror -Wno-unused-local-typedefs -g -Wall -Wextra -D_REENTRANT -fPIC -DLIBFTDI1 -DQT_PLUGIN -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -I../../interfaces -I../../midi/src/common -I/usr/include/libftdipp1 -I/usr/include/libusb-1.0 -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I. -I/usr/lib/qt/mkspecs/linux-g++ -o vinceusbdmx512.o vinceusbdmx512.cpp
g++ -c -pipe -Werror -Wno-unused-local-typedefs -g -Wall -Wextra -D_REENTRANT -fPIC -DLIBFTDI1 -DQT_PLUGIN -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -I../../interfaces -I../../midi/src/common -I/usr/include/libftdipp1 -I/usr/include/libusb-1.0 -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I. -I/usr/lib/qt/mkspecs/linux-g++ -o midiprotocol.o ../../midi/src/common/midiprotocol.cpp
g++ -c -pipe -Werror -Wno-unused-local-typedefs -g -Wall -Wextra -D_REENTRANT -fPIC -DLIBFTDI1 -DQT_PLUGIN -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -I../../interfaces -I../../midi/src/common -I/usr/include/libftdipp1 -I/usr/include/libusb-1.0 -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I. -I/usr/lib/qt/mkspecs/linux-g++ -o nanodmx.o nanodmx.cpp
g++ -c -pipe -Werror -Wno-unused-local-typedefs -g -Wall -Wextra -D_REENTRANT -fPIC -DLIBFTDI1 -DQT_PLUGIN -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -I../../interfaces -I../../midi/src/common -I/usr/include/libftdipp1 -I/usr/include/libusb-1.0 -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I. -I/usr/lib/qt/mkspecs/linux-g++ -o euroliteusbdmxpro.o euroliteusbdmxpro.cpp
g++ -c -pipe -Werror -Wno-unused-local-typedefs -g -Wall -Wextra -D_REENTRANT -fPIC -DLIBFTDI1 -DQT_PLUGIN -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -I../../interfaces -I../../midi/src/common -I/usr/include/libftdipp1 -I/usr/include/libusb-1.0 -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I. -I/usr/lib/qt/mkspecs/linux-g++ -o libftdi-interface.o libftdi-interface.cpp
libftdi-interface.cpp: Dans la fonction membre statique « static QList<DMXInterface*> LibFTDIInterface::interfaces(QList<DMXInterface*>) »:
libftdi-interface.cpp:138:37: erreur: « struct ftdi_context » n'a pas de membre nommé « usb_ctx »
  138 |     if (libusb_get_device_list(ftdi.usb_ctx, &devs) < 0)
      |                                     ^~~~~~~
libftdi-interface.cpp:182:37: erreur: ne peut convertir « libusb_device* » en « usb_device* »
  182 |         ftdi_usb_get_strings(&ftdi, dev, vend, 256, nme, 256, ser, 256);
      |                                     ^~~
      |                                     |
      |                                     libusb_device*
Dans le fichier inclus depuis libftdi-interface.h:24,
                 depuis libftdi-interface.cpp:31:
/usr/include/ftdi.h:376:76: note:   initialisation de l'argument 2 de « int ftdi_usb_get_strings(ftdi_context*, usb_device*, char*, int, char*, int, char*, int) »
  376 |     int ftdi_usb_get_strings(struct ftdi_context *ftdi, struct usb_device *dev,
      |                                                         ~~~~~~~~~~~~~~~~~~~^~~
Dans le fichier inclus depuis libftdi-interface.cpp:28:
/usr/include/libusb-1.0/libusb.h:944:8: note: le type classe « libusb_device » est incomplet
  944 | struct libusb_device;
      |        ^~~~~~~~~~~~~
make[2]: *** [Makefile:1063 : libftdi-interface.o] Erreur 1
make[2] : on quitte le répertoire « /home/drumslayer/git/qlcplus/plugins/dmxusb/src »
make[1]: *** [Makefile:47 : sub-src-make_first-ordered] Erreur 2
make[1] : on quitte le répertoire « /home/drumslayer/git/qlcplus/plugins/dmxusb »
make: *** [Makefile:60 : sub-dmxusb-make_first] Erreur 2

```

**Comment by mcuadros** [comment]
I have exactly the same version and I have the same issues:

```
home> pkg-config --modversion libftdi1    
1.5
home> pkg-config --modversion libusb-1.0            
1.0.24
home> pkg-config --modversion libusb    
0.1.12
```

**Comment by mcallegari** [comment]
I suspect there's something wrong with `-I/usr/include/libftdipp1`.

On Ubuntu it correctly includes headers from libftdi1, like this
`g++ -c -pipe -Werror -Wno-unused-local-typedefs -g -Wall -Wextra -D_REENTRANT -fPIC -DQMLUI -DLIBFTDI1 -DQT_PLUGIN -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -I../../interfaces -I../../midi/src/common -isystem /usr/include/libftdi1 -isystem /usr/include/libusb-1.0 -I/home/massimo/projects/Qt5.14.2/5.14.2/gcc_64/include -I/home/massimo/projects/Qt5.14.2/5.14.2/gcc_64/include/QtWidgets -I/home/massimo/projects/Qt5.14.2/5.14.2/gcc_64/include/QtGui -I/home/massimo/projects/Qt5.14.2/5.14.2/gcc_64/include/QtCore -I. -isystem /usr/include/libdrm -I/home/massimo/projects/Qt5.14.2/5.14.2/gcc_64/mkspecs/linux-g++ -o libftdi-interface.o libftdi-interface.cpp`

**Comment by kripton** [comment]
Possibly related. https://bugs.gentoo.org/766818 ?

**Comment by mcuadros** [comment]
I just tried to compile using `libftdi-1.4-4-x86_64.pkg.tar.xz ` and the error is the same:

```
/libftdipp1 -I/usr/include/libusb-1.0 -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I. -I/usr/lib/qt/mkspecs/linux-g++ -o libftdi-interface.o libftdi-interface.cpp
libftdi-interface.cpp: In static member function ‘static QList<DMXInterface*> LibFTDIInterface::interfaces(QList<DMXInterface*>)’:
libftdi-interface.cpp:138:37: error: ‘struct ftdi_context’ has no member named ‘usb_ctx’
  138 |     if (libusb_get_device_list(ftdi.usb_ctx, &devs) < 0)
      |                                     ^~~~~~~
libftdi-interface.cpp:182:37: error: cannot convert ‘libusb_device*’ to ‘usb_device*’
  182 |         ftdi_usb_get_strings(&ftdi, dev, vend, 256, nme, 256, ser, 256);
      |                                     ^~~
      |                                     |
      |                                     libusb_device*
In file included from libftdi-interface.h:24,
                 from libftdi-interface.cpp:31:
/usr/include/ftdi.h:376:76: note:   initializing argument 2 of ‘int ftdi_usb_get_strings(ftdi_context*, usb_device*, char*, int, char*, int, char*, int)’
  376 |     int ftdi_usb_get_strings(struct ftdi_context *ftdi, struct usb_device *dev,
      |                                                         ~~~~~~~~~~~~~~~~~~~^~~
In file included from libftdi-interface.cpp:28:
/usr/include/libusb-1.0/libusb.h:944:8: note: class type ‘libusb_device’ is incomplete
  944 | struct libusb_device;
      |        ^~~~~~~~~~~~~
```

**Comment by mcallegari** [comment]
Please do this
`locate libftdi1.pc`
and show me the content of the file. Again, I suspect there's something wrong with the pkgconfig resolution, pointing QLC+ to use the wrong header files (libftdipp1)

**Comment by Kuerbiskakteen** [comment]
I have the same issue on Archlinux.

The content of /usr/lib/pkgconfig/libftdi1.pc are:
`prefix=/usr
exec_prefix=/usr/bin
libdir=/usr/lib
includedir=/usr/include/libftdipp1

Name: libftdi1
Description: Library to program and control the FTDI USB controller
Requires: libusb-1.0
Version: 1.5
Libs: -L${libdir} -lftdi1
Cflags: -I${includedir}
`

**Comment by Dolpic** [comment]
That's where the error is, /usr/lib/pkgconfig/libftdi1.pc should have the line
`includedir=/usr/include/libftdipp1`
Replaced by
`includedir=/usr/include/libftdi1`
Which is indeed the right dependency.

I tested, and it worked, at least for me.

No idea why this file seems corrupted in Manjaro last upgrade tho...

**Comment by mcallegari** [comment]
@all Can I consider this a closed case then?

**Comment by Kuerbiskakteen** [comment]
At my computer dose it worke too.
