### ISSUE TITLE
[Windows] error when building with GCC 12.x

### ISSUE THREAD

**Issue by mcallegari** [mcallegari/qlcplus#1377]
This is the error log

```C++
g++ -c -fno-keep-inline-dllexport -march=pentium4 -mtune=generic -Wa,-mbig-obj -Werror -Wno-error=attributes -Wno-unused-local-typedefs -O2 -Wall -Wextra -Wextra -fexceptions -mthreads -DUNICODE -D_UNICODE -DWIN32 -DMINGW_HAS_SECURE_API=1 -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -I. -I../../../../msys64/mingw32/include/qt6 -I../../../../msys64/mingw32/include/qt6/QtGui -I../../../../msys64/mingw32/include/qt6/QtCore -Irelease -I/include -I../../../../msys64/mingw32/share/qt6/mkspecs/win32-g++  -o release/hpmprivate-win32.o hpmprivate-win32.cpp
In file included from C:/msys64/mingw32/include/qt6/QtCore/QtCore:33,
                 from hpmprivate-win32.cpp:27:
C:/msys64/mingw32/include/qt6/QtCore/qbitarray.h:18:33: error: 'size_t qHash(const QBitArray&, size_t)' redeclared without dllimport attribute after bein
g referenced with dll linkage [-Werror]
   18 |     friend Q_CORE_EXPORT size_t qHash(const QBitArray &key, size_t seed) noexcept;
      |                                 ^~~~~
In file included from C:/msys64/mingw32/include/qt6/QtCore/qcalendar.h:10,
                 from C:/msys64/mingw32/include/qt6/QtCore/QtCore:41:
C:/msys64/mingw32/include/qt6/QtCore/qlocale.h:1120:33: warning: 'size_t qHash(const QLocale&, size_t)' redeclared without dllimport attribute: previous
dllimport ignored [-Wattributes]
 1120 |     friend Q_CORE_EXPORT size_t qHash(const QLocale &key, size_t seed) noexcept;
      |                                 ^~~~~
In file included from C:/msys64/mingw32/include/qt6/QtCore/qcborvalue.h:11,
                 from C:/msys64/mingw32/include/qt6/QtCore/qcborarray.h:7,
                 from C:/msys64/mingw32/include/qt6/QtCore/QtCore:42:
C:/msys64/mingw32/include/qt6/QtCore/qregularexpression.h:150:33: warning: 'size_t qHash(const QRegularExpression&, size_t)' redeclared without dllimport
 attribute: previous dllimport ignored [-Wattributes]
  150 |     friend Q_CORE_EXPORT size_t qHash(const QRegularExpression &key, size_t seed) noexcept;
      |                                 ^~~~~
In file included from C:/msys64/mingw32/include/qt6/QtCore/qcborvalue.h:15:
C:/msys64/mingw32/include/qt6/QtCore/qurl.h:266:33: warning: 'size_t qHash(const QUrl&, size_t)' redeclared without dllimport attribute: previous dllimpo
rt ignored [-Wattributes]
  266 |     friend Q_CORE_EXPORT size_t qHash(const QUrl &url, size_t seed) noexcept;
      |                                 ^~~~~
In file included from C:/msys64/mingw32/include/qt6/QtCore/qlibraryinfo.h:9,
                 from C:/msys64/mingw32/include/qt6/QtCore/QtCore:133:
C:/msys64/mingw32/include/qt6/QtCore/qversionnumber.h:299:39: warning: 'QDataStream& operator>>(QDataStream&, QVersionNumber&)' redeclared without dllimp
ort attribute: previous dllimport ignored [-Wattributes]
  299 |     friend Q_CORE_EXPORT QDataStream& operator>>(QDataStream &in, QVersionNumber &version);
      |                                       ^~~~~~~~
C:/msys64/mingw32/include/qt6/QtCore/qversionnumber.h:301:33: warning: 'size_t qHash(const QVersionNumber&, size_t)' redeclared without dllimport attribu
te: previous dllimport ignored [-Wattributes]
  301 |     friend Q_CORE_EXPORT size_t qHash(const QVersionNumber &key, size_t seed);
      |                                 ^~~~~
In file included from C:/msys64/mingw32/include/qt6/QtCore/qmimedatabase.h:8,
                 from C:/msys64/mingw32/include/qt6/QtCore/QtCore:148:
C:/msys64/mingw32/include/qt6/QtCore/qmimetype.h:86:33: warning: 'size_t qHash(const QMimeType&, size_t)' redeclared without dllimport attribute: previou
s dllimport ignored [-Wattributes]
   86 |     friend Q_CORE_EXPORT size_t qHash(const QMimeType &key, size_t seed) noexcept;
      |                                 ^~~~~
In file included from C:/msys64/mingw32/include/qt6/QtCore/QtCore:266:
C:/msys64/mingw32/include/qt6/QtCore/qurlquery.h:71:33: warning: 'size_t qHash(const QUrlQuery&, size_t)' redeclared without dllimport attribute: previou
s dllimport ignored [-Wattributes]
   71 |     friend Q_CORE_EXPORT size_t qHash(const QUrlQuery &key, size_t seed) noexcept;
      |                                 ^~~~~
```

**Comment by MonsieurNaexec** [comment]
Hi,
Will this be fixed any time soon?
I tried to install the environment on a clean windows 11 install and got stuck with this errors...
As I currently have no development environment, I can't see any way to compile qlcplus on Windows at all :/

**Comment by mcallegari** [comment]
You can build with Qt 6.4.x or apply the workaround used here:
https://github.com/mcallegari/qlcplus/blob/master/appveyor.yml

**Comment by javierdc** [comment]
Hi, I installed Qt 6.4.x but still getting these errors:

$ make
cd hotplugmonitor/ && ( test -e Makefile || C:/msys64/mingw32/bin/qmake.exe -o Makefile C:/Qt/qlcplus/hotplugmonitor/hotplugmonitor.pro ) && make -f Makefile
make[1]: Entering directory '/c/Qt/qlcplus/hotplugmonitor'
cd src/ && ( test -e Makefile || C:/msys64/mingw32/bin/qmake.exe -o Makefile C:/Qt/qlcplus/hotplugmonitor/src/src.pro ) && make -f Makefile
make[2]: Entering directory '/c/Qt/qlcplus/hotplugmonitor/src'
make -f Makefile.Debug
make[3]: Entering directory '/c/Qt/qlcplus/hotplugmonitor/src'
g++ -c -fno-keep-inline-dllexport -march=pentium4 -mtune=generic -Wa,-mbig-obj -Werror -Wno-unused-local-typedefs -g -Wall -Wextra -Wextra -fexceptions -mthreads -DUNICODE -D_UNICODE -DWIN32 -DMINGW_HAS_SECURE_API=1 -DQT_GUI_LIB -DQT_CORE_LIB -I. -I../../../../msys64/mingw32/include/QtGui -I../../../../msys64/mingw32/include/QtCore -Idebug -I/include -I../../../../msys64/mingw32/share/qt5/mkspecs/win32-g++  -o debug/hpmprivate-win32.o hpmprivate-win32.cpp
In file included from C:/msys64/mingw32/include/QtCore/QtCore:31,
                 from hpmprivate-win32.cpp:27:
C:/msys64/mingw32/include/QtCore/qbitarray.h:53:31: error: 'uint qHash(const QBitArray&, uint)' redeclared without dllimport attribute after being referenced with dll linkage [-Werror]
   53 |     friend Q_CORE_EXPORT uint qHash(const QBitArray &key, uint seed) noexcept;
      |                               ^~~~~
In file included from C:/msys64/mingw32/include/QtCore/QtCore:264:
C:/msys64/mingw32/include/QtCore/qurlquery.h:112:31: error: 'uint qHash(const QUrlQuery&, uint)' redeclared without dllimport attribute: previous dllimport ignored [-Werror=attributes]
  112 |     friend Q_CORE_EXPORT uint qHash(const QUrlQuery &key, uint seed) noexcept;
      |                               ^~~~~
cc1plus.exe: all warnings being treated as errors
make[3]: *** [Makefile.Debug:332: debug/hpmprivate-win32.o] Error 1
make[3]: Leaving directory '/c/Qt/qlcplus/hotplugmonitor/src'
make[2]: *** [Makefile:45: debug] Error 2
make[2]: Leaving directory '/c/Qt/qlcplus/hotplugmonitor/src'
make[1]: *** [Makefile:51: sub-src-make_first-ordered] Error 2
make[1]: Leaving directory '/c/Qt/qlcplus/hotplugmonitor'
make: *** [Makefile:58: sub-hotplugmonitor-make_first-ordered] Error 2

Any suggestions?

**Comment by mcallegari** [comment]
That's because you're still building with Qt5. (...msys64/mingw32/share/**qt5**/mkspecs...)
You need to use `qmake-qt6` to build with Qt 6.x

**Comment by javierdc** [comment]
thanks for the reply, I tried with qmake-qt6 but still got errors:

$ make
cd hotplugmonitor/ && ( test -e Makefile || C:/msys64/mingw32/bin/qmake-qt6.exe -o Makefile C:/Qt/qlcplus/hotplugmonitor/hotplugmonitor.pro ) && make -f Makefile
make[1]: Entering directory '/c/Qt/qlcplus/hotplugmonitor'
cd src/ && ( test -e Makefile || C:/msys64/mingw32/bin/qmake-qt6.exe -o Makefile C:/Qt/qlcplus/hotplugmonitor/src/src.pro ) && make -f Makefile
make[2]: Entering directory '/c/Qt/qlcplus/hotplugmonitor/src'
make -f Makefile.Debug
make[3]: Entering directory '/c/Qt/qlcplus/hotplugmonitor/src'
g++ -c -fno-keep-inline-dllexport -march=pentium4 -mtune=generic -Wa,-mbig-obj -Werror -Wno-unused-local-typedefs -g -Wall -Wextra -Wextra -fexceptions -mthreads -DUNICODE -D_UNICODE -DWIN32 -DMINGW_HAS_SECURE_API=1 -DQT_GUI_LIB -DQT_CORE_LIB -I. -I../../../../msys64/mingw32/include/qt6 -I../../../../msys64/mingw32/include/qt6/QtGui -I../../../../msys64/mingw32/include/qt6/QtCore -Idebug -I/include -I../../../../msys64/mingw32/share/qt6/mkspecs/win32-g++  -o debug/hpmprivate-win32.o hpmprivate-win32.cpp
In file included from C:/msys64/mingw32/include/qt6/QtCore/QtCore:33,
                 from hpmprivate-win32.cpp:27:
C:/msys64/mingw32/include/qt6/QtCore/qbitarray.h:18:33: error: 'size_t qHash(const QBitArray&, size_t)' redeclared without dllimport attribute after being referenced with dll linkage [-Werror]
   18 |     friend Q_CORE_EXPORT size_t qHash(const QBitArray &key, size_t seed) noexcept;
      |                                 ^~~~~
In file included from C:/msys64/mingw32/include/qt6/QtCore/qcalendar.h:10,
                 from C:/msys64/mingw32/include/qt6/QtCore/QtCore:41:
C:/msys64/mingw32/include/qt6/QtCore/qlocale.h:1120:33: error: 'size_t qHash(const QLocale&, size_t
' redeclared without dllimport attribute: previous dllimport ignored [-Werror=attributes]
 1120 |     friend Q_CORE_EXPORT size_t qHash(const QLocale &key, size_t seed) noexcept;
      |                                 ^~~~~
In file included from C:/msys64/mingw32/include/qt6/QtCore/qcborvalue.h:11,
                 from C:/msys64/mingw32/include/qt6/QtCore/qcborarray.h:7,
                 from C:/msys64/mingw32/include/qt6/QtCore/QtCore:42:
C:/msys64/mingw32/include/qt6/QtCore/qregularexpression.h:150:33: error: 'size_t qHash(const QRegularExpression&, size_t)' redeclared without dllimport attribute: previous dllimport ignored [-Werror=attributes]
  150 |     friend Q_CORE_EXPORT size_t qHash(const QRegularExpression &key, size_t seed) noexcept;
      |                                 ^~~~~
In file included from C:/msys64/mingw32/include/qt6/QtCore/qcborvalue.h:15:
C:/msys64/mingw32/include/qt6/QtCore/qurl.h:266:33: error: 'size_t qHash(const QUrl&, size_t)' redeclared without dllimport attribute: previous dllimport ignored [-Werror=attributes]
  266 |     friend Q_CORE_EXPORT size_t qHash(const QUrl &url, size_t seed) noexcept;
      |                                 ^~~~~
In file included from C:/msys64/mingw32/include/qt6/QtCore/qlibraryinfo.h:9,
                 from C:/msys64/mingw32/include/qt6/QtCore/QtCore:133:
C:/msys64/mingw32/include/qt6/QtCore/qversionnumber.h:299:39: error: 'QDataStream& operator>>(QDataStream&, QVersionNumber&)' redeclared without dllimport attribute: previous dllimport ignored [-Werror=attributes]
  299 |     friend Q_CORE_EXPORT QDataStream& operator>>(QDataStream &in, QVersionNumber &version);
      |                                       ^~~~~~~~
C:/msys64/mingw32/include/qt6/QtCore/qversionnumber.h:301:33: error: 'size_t qHash(const QVersionNumber&, size_t)' redeclared without dllimport attribute: previous dllimport ignored [-Werror=attributes]
  301 |     friend Q_CORE_EXPORT size_t qHash(const QVersionNumber &key, size_t seed);
      |                                 ^~~~~
In file included from C:/msys64/mingw32/include/qt6/QtCore/qmimedatabase.h:8,
                 from C:/msys64/mingw32/include/qt6/QtCore/QtCore:148:
C:/msys64/mingw32/include/qt6/QtCore/qmimetype.h:86:33: error: 'size_t qHash(const QMimeType&, size_t)' redeclared without dllimport attribute: previous dllimport ignored [-Werror=attributes]
   86 |     friend Q_CORE_EXPORT size_t qHash(const QMimeType &key, size_t seed) noexcept;
      |                                 ^~~~~
In file included from C:/msys64/mingw32/include/qt6/QtCore/QtCore:266:
C:/msys64/mingw32/include/qt6/QtCore/qurlquery.h:71:33: error: 'size_t qHash(const QUrlQuery&, size_t)' redeclared without dllimport attribute: previous dllimport ignored [-Werror=attributes]
   71 |     friend Q_CORE_EXPORT size_t qHash(const QUrlQuery &key, size_t seed) noexcept;
      |                                 ^~~~~
cc1plus.exe: all warnings being treated as errors
make[3]: *** [Makefile.Debug:532: debug/hpmprivate-win32.o] Error 1
make[3]: Leaving directory '/c/Qt/qlcplus/hotplugmonitor/src'
make[2]: *** [Makefile:45: debug] Error 2
make[2]: Leaving directory '/c/Qt/qlcplus/hotplugmonitor/src'
make[1]: *** [Makefile:51: sub-src-make_first-ordered] Error 2
make[1]: Leaving directory '/c/Qt/qlcplus/hotplugmonitor'
make: *** [Makefile:58: sub-hotplugmonitor-make_first-ordered] Error 2

**Comment by mcallegari** [comment]
Again, see https://github.com/mcallegari/qlcplus/issues/1377#issuecomment-1369060292

**Comment by javierdc** [comment]
Sorry if these are dumb questions, I'm still earning MSYS and Qt. I was able to compile using qt6 although I had to use mingw64 (with mingw-w64-x86_64-qt6 package) since MSYS didn't have the qt6 packages with all the libs needed for mingw32 (mingw32/mingw-w64-i686-qt6). The problem with this is that the ftdi driver from i386 breaks during compile so switched to amd64. 

After compile I can run qlc without issues (so far) except that if I connect the open dmx usb, qlc breaks at runtime. If I don't use the ftdi, then everything seems to be working.

Do I'm missing some config setting so I can use the driver from i386? Do I need to go back to mingw32, and if so and guidance on how to get all Qt6 packages needed?

**Comment by javierdc** [comment]
Let me clarify my question:
For compiling using qt6 do I need to use mingw32? or mingw64

**Comment by mcallegari** [comment]
Excuse me but you hijacked this ticket with questions about building on Windows, which was not the purpose of this ticket.
An issue get either resolved by me or someone else or commented with suggestions and/or improvements.

You should have posted your problem on the forums and discussed there. This is a place for developers willing to help the project.
Now, why do you want to build with Qt6 if the Qt5 is just fine?
You can build on Qt6 adopting the same workaround for Qt5. I never built a 64bit version of QLC+ on Windows, but I guess the D2XX library needs a different treatment (did you see there's an amd64 folder?)
But again, why you insist so much with Qt6?

**Comment by javierdc** [comment]
I do want to contribute to the project. Given that the project is moving to qt6, I wanted to build it using qt6. I can build in 64 using the amd64 but fails during runtime when trying to open the port.

I did try the workaround using qt6 and 32bit but was not able to compile since it does not find QtMultimedia, I guess I'll need to build it since was not able to find such package precompiled for 32.

**Comment by Itay-Lifshitz** [comment]
I guess we can close this issue with my last [PR](https://github.com/mcallegari/qlcplus/pull/1418).
I get no such issues while compiling with GCC 12.2 in MSYS2.
