### ISSUE TITLE
Unable to build on windows (rgbscript_test.cpp.obj)

### ISSUE THREAD

**Issue by LeChat109** [mcallegari/qlcplus#1833]
**Describe the bug**

**To Reproduce**
1. Follow the wiki building instructions for qlc5 with qt6.10.0
2. cmake does well
3. execute ninja
4. it gives me the error and opens translate.sh in my text editor

**Expected behavior**
Ninja succeed

**Screenshots**

<img width="2559" height="1389" alt="Image" src="https://github.com/user-attachments/assets/0ddc507c-35db-4a9d-b381-237f7a908162" />

**Desktop (please complete the following information):**
 - OS: Windows
 - QLC+ Version release 5.0.0
 - Qt 6.10.0

**Additional context**
i think that translate.sh normally runs in MINGW64 but for some reasons, it executes "translate.sh" somewere in windows, because .sh files arent working on windows, it tries to open it as a text file.

command line : 
```
$ ninja
[0/5] Translating qmlui translations...
[main 2025-10-13T00:32:44.268Z] update#setState idle
[1/5] Building CXX object engine/test/qlcfixturedefcache/CMakeFiles/qlcfixturedefcache_test.dir/qlcfixturedefcache_test.cpp.obj
FAILED: [code=1] engine/test/qlcfixturedefcache/CMakeFiles/qlcfixturedefcache_test.dir/qlcfixturedefcache_test.cpp.obj
C:\msys64\mingw64\bin\c++.exe -DHAS_FFTW3 -DMINGW_HAS_SECURE_API=1 -DQMLUI -DQT_CORE_LIB -DQT_GUI_LIB -DQT_MULTIMEDIA_LIB -DQT_NEEDS_QMAIN -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_QMLINTEGRATION_LIB -DQT_QML_LIB -DQT_TESTCASE_BUILDDIR=\"C:/projects/qlcplus/build/engine/test/qlcfixturedefcache\" -DQT_TESTCASE_SOURCEDIR=\"C:/projects/qlcplus/engine/test/qlcfixturedefcache\" -DQT_TESTLIB_LIB -DQT_WIDGETS_LIB -DUNICODE -DWIN32 -DWIN64 -D_ENABLE_EXTENDED_ALIGNED_STORAGE -D_UNICODE -D_WIN64 -IC:/projects/qlcplus/build/engine/test/qlcfixturedefcache -IC:/projects/qlcplus/engine/test/qlcfixturedefcache -IC:/projects/qlcplus/build/engine/test/qlcfixturedefcache/qlcfixturedefcache_test_autogen/include -IC:/projects/qlcplus/engine/test/qlcfixturedefcache/../../../plugins/interfaces -IC:/projects/qlcplus/engine/test/qlcfixturedefcache/../../src -IC:/projects/qlcplus/engine/src/../../plugins/interfaces -IC:/projects/qlcplus/engine/src/../audio/src -IC:/projects/qlcplus/engine/src/../../hotplugmonitor/src -IC:/projects/qlcplus/engine/src -isystem C:/Qt/6.10.0/mingw_64/include/QtCore -isystem C:/Qt/6.10.0/mingw_64/include -isystem C:/Qt/6.10.0/mingw_64/mkspecs/win32-g++ -isystem C:/Qt/6.10.0/mingw_64/include/QtGui -isystem C:/Qt/6.10.0/mingw_64/include/QtTest -isystem C:/Qt/6.10.0/mingw_64/include/QtMultimedia -isystem C:/Qt/6.10.0/mingw_64/include/QtNetwork -isystem C:/Qt/6.10.0/mingw_64/include/QtWidgets -isystem C:/Qt/6.10.0/mingw_64/include/QtQml -isystem C:/Qt/6.10.0/mingw_64/include/QtQmlIntegration -Werror -Wextra -Wall -O3 -DNDEBUG -MD -MT engine/test/qlcfixturedefcache/CMakeFiles/qlcfixturedefcache_test.dir/qlcfixturedefcache_test.cpp.obj -MF engine\test\qlcfixturedefcache\CMakeFiles\qlcfixturedefcache_test.dir\qlcfixturedefcache_test.cpp.obj.d -o engine/test/qlcfixturedefcache/CMakeFiles/qlcfixturedefcache_test.dir/qlcfixturedefcache_test.cpp.obj -c C:/projects/qlcplus/engine/test/qlcfixturedefcache/qlcfixturedefcache_test.cpp
C:/projects/qlcplus/engine/test/qlcfixturedefcache/qlcfixturedefcache_test.cpp: In member function 'void QLCFixtureDefCache_Test::storeDef()':
C:/projects/qlcplus/engine/test/qlcfixturedefcache/qlcfixturedefcache_test.cpp:240:17: error: ignoring return value of 'virtual bool QFile::open(QIODeviceBase::OpenMode)', declared with attribute 'nodiscard' [-Werror=unused-result]
  240 |     defFile.open(QIODevice::ReadOnly | QIODevice::Text);
      |     ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from C:/Qt/6.10.0/mingw_64/include/QtCore/qdir.h:11,
                 from C:/Qt/6.10.0/mingw_64/include/QtCore/QtCore:91,
                 from C:/Qt/6.10.0/mingw_64/include/QtTest/QtTestDepends:3,
                 from C:/Qt/6.10.0/mingw_64/include/QtTest/QtTest:3,
                 from C:/projects/qlcplus/engine/test/qlcfixturedefcache/qlcfixturedefcache_test.cpp:20:
C:/Qt/6.10.0/mingw_64/include/QtCore/qfile.h:291:32: note: declared here
  291 |     QFILE_MAYBE_NODISCARD bool open(OpenMode flags) override;
      |                                ^~~~
cc1plus.exe: all warnings being treated as errors
[2/5] Building CXX object engine/test/rgbscript/CMakeFiles/rgbscript_test.dir/rgbscript_test.cpp.obj
FAILED: [code=1] engine/test/rgbscript/CMakeFiles/rgbscript_test.dir/rgbscript_test.cpp.obj
C:\msys64\mingw64\bin\c++.exe -DHAS_FFTW3 -DMINGW_HAS_SECURE_API=1 -DQMLUI -DQT_CORE_LIB -DQT_GUI_LIB -DQT_MULTIMEDIA_LIB -DQT_NEEDS_QMAIN -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_QMLINTEGRATION_LIB -DQT_QML_LIB -DQT_TESTCASE_BUILDDIR=\"C:/projects/qlcplus/build/engine/test/rgbscript\" -DQT_TESTCASE_SOURCEDIR=\"C:/projects/qlcplus/engine/test/rgbscript\" -DQT_TESTLIB_LIB -DQT_WIDGETS_LIB -DUNICODE -DWIN32 -DWIN64 -D_ENABLE_EXTENDED_ALIGNED_STORAGE -D_UNICODE -D_WIN64 -IC:/projects/qlcplus/build/engine/test/rgbscript -IC:/projects/qlcplus/engine/test/rgbscript -IC:/projects/qlcplus/build/engine/test/rgbscript/rgbscript_test_autogen/include -IC:/projects/qlcplus/engine/test/rgbscript/../../../plugins/interfaces -IC:/projects/qlcplus/engine/test/rgbscript/../../src -IC:/projects/qlcplus/engine/test/rgbscript/../mastertimer -IC:/projects/qlcplus/engine/src/../../plugins/interfaces -IC:/projects/qlcplus/engine/src/../audio/src -IC:/projects/qlcplus/engine/src/../../hotplugmonitor/src -IC:/projects/qlcplus/engine/src -isystem C:/Qt/6.10.0/mingw_64/include/QtCore -isystem C:/Qt/6.10.0/mingw_64/include -isystem C:/Qt/6.10.0/mingw_64/mkspecs/win32-g++ -isystem C:/Qt/6.10.0/mingw_64/include/QtGui -isystem C:/Qt/6.10.0/mingw_64/include/QtTest -isystem C:/Qt/6.10.0/mingw_64/include/QtMultimedia -isystem C:/Qt/6.10.0/mingw_64/include/QtNetwork -isystem C:/Qt/6.10.0/mingw_64/include/QtWidgets -isystem C:/Qt/6.10.0/mingw_64/include/QtQml -isystem C:/Qt/6.10.0/mingw_64/include/QtQmlIntegration -Werror -Wextra -Wall -O3 -DNDEBUG -MD -MT engine/test/rgbscript/CMakeFiles/rgbscript_test.dir/rgbscript_test.cpp.obj -MF engine\test\rgbscript\CMakeFiles\rgbscript_test.dir\rgbscript_test.cpp.obj.d -o engine/test/rgbscript/CMakeFiles/rgbscript_test.dir/rgbscript_test.cpp.obj -c C:/projects/qlcplus/engine/test/rgbscript/rgbscript_test.cpp
C:/projects/qlcplus/engine/test/rgbscript/rgbscript_test.cpp: In member function 'void RGBScript_Test::scripts()':
C:/projects/qlcplus/engine/test/rgbscript/rgbscript_test.cpp:97:17: error: ignoring return value of 'virtual bool QFile::open(QIODeviceBase::OpenMode)', declared with attribute 'nodiscard' [-Werror=unused-result]
   97 |     proFile.open(QIODevice::ReadWrite);
      |     ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
In file included from C:/Qt/6.10.0/mingw_64/include/QtCore/qdir.h:11,
                 from C:/Qt/6.10.0/mingw_64/include/QtCore/QtCore:91,
                 from C:/Qt/6.10.0/mingw_64/include/QtTest/QtTestDepends:3,
                 from C:/Qt/6.10.0/mingw_64/include/QtTest/QtTest:3,
                 from C:/projects/qlcplus/engine/test/rgbscript/rgbscript_test.cpp:20:
C:/Qt/6.10.0/mingw_64/include/QtCore/qfile.h:291:32: note: declared here
  291 |     QFILE_MAYBE_NODISCARD bool open(OpenMode flags) override;
      |                                ^~~~
cc1plus.exe: all warnings being treated as errors
[main 2025-10-13T00:33:14.273Z] update#setState checking for updates
[main 2025-10-13T00:33:14.319Z] update#setState idle
[main 2025-10-13T00:33:36.333Z] Extension host with pid 24396 exited with code: 0, signal: unknown.
[3/5] Translating qmlui translations...
ninja: build stopped: subcommand failed.
```

**Comment by mcallegari** [comment]
I haven't tried to build with Qt 6.10 yet.
The fix might be this
https://github.com/mcallegari/qlcplus/pull/1832

**Comment by LeChat109** [comment]
i just tried with that fix (by pulling the master) and the same happends :

```
$ ninja
[0/3] Translating qmlui translations...
[main 2025-10-13T13:46:41.261Z] update#setState idle
[1/3] Building CXX object qmlui/CMakeFiles/qlcplus-qml.dir/main.cpp.obj
FAILED: [code=1] qmlui/CMakeFiles/qlcplus-qml.dir/main.cpp.obj
C:\msys64\mingw64\bin\c++.exe -DHAS_FFTW3 -DMINGW_HAS_SECURE_API=1 -DQMLUI -DQT_3DCORE_LIB -DQT_3DEXTRAS_LIB -DQT_3DINPUT_LIB -DQT_3DLOGIC_LIB -DQT_3DQUICKEXTRAS_LIB -DQT_3DQUICK_LIB -DQT_3DRENDER_LIB -DQT_CONCURRENT_LIB -DQT_CORE_LIB -DQT_GUI_LIB -DQT_MULTIMEDIAWIDGETS_LIB -DQT_MULTIMEDIA_LIB -DQT_NEEDS_QMAIN -DQT_NETWORK_LIB -DQT_OPENGL_LIB -DQT_PRINTSUPPORT_LIB -DQT_QMLINTEGRATION_LIB -DQT_QMLMETA_LIB -DQT_QMLMODELS_LIB -DQT_QMLWORKERSCRIPT_LIB -DQT_QML_LIB -DQT_QUICK_LIB -DQT_SVG_LIB -DQT_WIDGETS_LIB -DUNICODE -DWIN32 -DWIN64 -D_ENABLE_EXTENDED_ALIGNED_STORAGE -D_UNICODE -D_WIN64 -IC:/projects/qlcplus/build/qmlui -IC:/projects/qlcplus/qmlui -IC:/projects/qlcplus/build/qmlui/qlcplus-qml_autogen/include -IC:/projects/qlcplus/qmlui/../engine/audio/src -IC:/projects/qlcplus/qmlui/../engine/src -IC:/projects/qlcplus/qmlui/../plugins/interfaces -IC:/projects/qlcplus/qmlui/../plugins/midi/src/common -IC:/projects/qlcplus/qmlui/fixtureeditor -IC:/projects/qlcplus/qmlui/tardis -IC:/projects/qlcplus/qmlui/virtualconsole -IC:/projects/qlcplus/engine/src/../../plugins/interfaces -IC:/projects/qlcplus/engine/src/../audio/src -IC:/projects/qlcplus/engine/src/../../hotplugmonitor/src -IC:/projects/qlcplus/engine/src -isystem C:/Qt/6.10.0/mingw_64/include/Qt3DCore -isystem C:/Qt/6.10.0/mingw_64/include -isystem C:/Qt/6.10.0/mingw_64/include/QtConcurrent -isystem C:/Qt/6.10.0/mingw_64/include/QtCore -isystem C:/Qt/6.10.0/mingw_64/mkspecs/win32-g++ -isystem C:/Qt/6.10.0/mingw_64/include/QtGui -isystem C:/Qt/6.10.0/mingw_64/include/QtNetwork -isystem C:/Qt/6.10.0/mingw_64/include/Qt3DInput -isystem C:/Qt/6.10.0/mingw_64/include/Qt3DQuick -isystem C:/Qt/6.10.0/mingw_64/include/Qt3DCore/6.10.0 -isystem C:/Qt/6.10.0/mingw_64/include/Qt3DCore/6.10.0/Qt3DCore -isystem C:/Qt/6.10.0/mingw_64/include/QtCore/6.10.0 -isystem C:/Qt/6.10.0/mingw_64/include/QtCore/6.10.0/QtCore -isystem C:/Qt/6.10.0/mingw_64/include/QtGui/6.10.0 -isystem C:/Qt/6.10.0/mingw_64/include/QtGui/6.10.0/QtGui -isystem C:/Qt/6.10.0/mingw_64/include/QtQml -isystem C:/Qt/6.10.0/mingw_64/include/QtQmlIntegration -isystem C:/Qt/6.10.0/mingw_64/include/QtQuick -isystem C:/Qt/6.10.0/mingw_64/include/QtQmlMeta -isystem C:/Qt/6.10.0/mingw_64/include/QtQmlModels -isystem C:/Qt/6.10.0/mingw_64/include/QtQmlWorkerScript -isystem C:/Qt/6.10.0/mingw_64/include/QtOpenGL -isystem C:/Qt/6.10.0/mingw_64/include/Qt3DQuickExtras -isystem C:/Qt/6.10.0/mingw_64/include/Qt3DExtras -isystem C:/Qt/6.10.0/mingw_64/include/Qt3DLogic -isystem C:/Qt/6.10.0/mingw_64/include/Qt3DRender -isystem C:/Qt/6.10.0/mingw_64/include/QtMultimedia -isystem C:/Qt/6.10.0/mingw_64/include/QtMultimediaWidgets -isystem C:/Qt/6.10.0/mingw_64/include/QtWidgets -isystem C:/Qt/6.10.0/mingw_64/include/QtPrintSupport -isystem C:/Qt/6.10.0/mingw_64/include/QtSvg -Werror -Wextra -Wall -g -MD -MT qmlui/CMakeFiles/qlcplus-qml.dir/main.cpp.obj -MF qmlui\CMakeFiles\qlcplus-qml.dir\main.cpp.obj.d -o qmlui/CMakeFiles/qlcplus-qml.dir/main.cpp.obj -c C:/projects/qlcplus/qmlui/main.cpp
C:/projects/qlcplus/qmlui/main.cpp: In function 'int qMain(int, char**)':
C:/projects/qlcplus/qmlui/main.cpp:122:21: error: ignoring return value of 'virtual bool QFile::open(QIODeviceBase::OpenMode)', declared with attribute 'nodiscard' [-Werror=unused-result]
  122 |         logFile.open(QIODevice::Append);
      |         ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
In file included from C:/Qt/6.10.0/mingw_64/include/QtCore/QFile:1,
                 from C:/projects/qlcplus/engine/src/doc.h:27,
                 from C:/projects/qlcplus/qmlui/app.h:27,
                 from C:/projects/qlcplus/qmlui/main.cpp:26:
C:/Qt/6.10.0/mingw_64/include/QtCore/qfile.h:291:32: note: declared here
  291 |     QFILE_MAYBE_NODISCARD bool open(OpenMode flags) override;
      |                                ^~~~
cc1plus.exe: all warnings being treated as errors
[main 2025-10-13T13:46:44.724Z] Extension host with pid 15644 exited with code: 0, signal: unknown.
[2/3] Translating qmlui translations...
ninja: build stopped: subcommand failed.
```

next try worked (almost) fine with qt 6.9.3
