### PR TITLE
Another Qt5 deprecation fix (QMutex)

### PR DESCRIPTION
**Pull request by edogawa23**

### CODE REVIEW

**Comment by mcallegari** [comment]
Hi, thanks for this.
Do you know if this is because of Qt 5.15.x or newer compilers?

**Comment by edogawa23** [comment]
Sorry - no idea, all I remember is that at some point a few months ago I suddenly got that deprecation error, then read the QMutex class documentation and found out about the API change/new class introduced in 5.14. I don't remember whether Qt5 or gcc had gotten an update in my openSUSE Tumbleweed at that time.
See [https://doc.qt.io/qt-5/qrecursivemutex.html](url)

**Comment by mcallegari** [comment]
I think it's a compiler flag, cause I always build with Qt 5.14.2 and never encounter this.
Would be nice to know also the compiler version just to track this down.

**Comment by edogawa23** [comment]
Here is the error I get with original code, I might be wrong but I think Qt did as usual, introduce the new class in 5.14 and deprecate old behaviour somewhere during 5.15.x  :

g++ -c -pipe -Werror -Wno-unused-local-typedefs -g -Wall -Wextra -D_REENTRANT -fPIC -DLIBFTDI1 -DLIBFTDI1_5 -DQT_PLUGIN -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -I../../interfaces -I../../midi/src/common -I/usr/include/libftdi1 -I/usr/include/libusb-1.0 -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I. -I/usr/lib64/qt5/mkspecs/linux-g++ -o enttecdmxusbpro.o enttecdmxusbpro.cpp
enttecdmxusbpro.cpp: In constructor ‘EnttecDMXUSBPro::EnttecDMXUSBPro(DMXInterface*, quint32, quint32)’:
enttecdmxusbpro.cpp:37:7: error: ‘QMutex::QMutex(QMutex::RecursionMode)’ is deprecated: Use QRecursiveMutex instead of a recursive QMutex [-Werror=deprecated-declarations]
   37 |     , m_outputMutex(QMutex::Recursive)
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/qt5/QtCore/QMutex:1,
                 from enttecdmxusbpro.h:25,
                 from enttecdmxusbpro.cpp:21:
/usr/include/qt5/QtCore/qmutex.h:140:14: note: declared here
  140 |     explicit QMutex(RecursionMode mode);
      |              ^~~~~~
cc1plus: all warnings being treated as errors
make: *** [Makefile:1002: enttecdmxusbpro.o] Fehler 1

Here's my compiler info:

bash-5.1$ g++ -v
Using built-in specs.
COLLECT_GCC=/usr/bin/g++
COLLECT_LTO_WRAPPER=/usr/lib64/gcc/x86_64-suse-linux/11/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:amdgcn-amdhsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-suse-linux
Configured with: ../configure --prefix=/usr --infodir=/usr/share/info --mandir=/usr/share/man --libdir=/usr/lib64 --libexecdir=/usr/lib64 --enable-languages=c,c++,objc,fortran,obj-c++,ada,go,d,jit --enable-offload-targets=nvptx-none,amdgcn-amdhsa, --without-cuda-driver --enable-host-shared --enable-checking=release --disable-werror --with-gxx-include-dir=/usr/include/c++/11 --enable-ssp --disable-libssp --disable-libvtv --enable-cet=auto --disable-libcc1 --enable-plugin --with-bugurl=https://bugs.opensuse.org/ --with-pkgversion='SUSE Linux' --with-slibdir=/lib64 --with-system-zlib --enable-libstdcxx-allocator=new --disable-libstdcxx-pch --enable-libphobos --enable-version-specific-runtime-libs --with-gcc-major-version-only --enable-linker-build-id --enable-linux-futex --enable-gnu-indirect-function --program-suffix=-11 --without-system-libunwind --enable-multilib --with-arch-32=x86-64 --with-tune=generic --with-build-config=bootstrap-lto-lean --enable-link-mutex --build=x86_64-suse-linux --host=x86_64-suse-linux
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 11.2.1 20220103 [revision d4a1d3c4b377f1d4acb34fe1b55b5088a3f293f6] (SUSE Linux) 
bash-5.1$

**Comment by mcallegari** [comment]
GCC 11 is quite recent. I suspected that. Thanks 👍
